In [1]:
from accutuning_helpers.feature_engineering import AccutuningChemicalConverter

In [2]:
bace = pd.read_csv('bace.csv')

In [3]:
bace

,mol,CID,Class,Model,pIC50,MW,AlogP,HBA,HBD,RB,...,PEOE6 (PEOE6),PEOE7 (PEOE7),PEOE8 (PEOE8),PEOE9 (PEOE9),PEOE10 (PEOE10),PEOE11 (PEOE11),PEOE12 (PEOE12),PEOE13 (PEOE13),PEOE14 (PEOE14),canvasUID
0,O1CC[C@@H](NC(=O)[C@@H](Cc2cc3cc(ccc3nc2N)-c2c...,BACE_1,1,Train,9.154901,431.56979,4.4014,3,2,5,...,53.205711,78.640335,226.855410,107.434910,37.133846,0.000000,7.980170,0.000000,0.000000,1
1,Fc1cc(cc(F)c1)C[C@H](NC(=O)[C@@H](N1CC[C@](NC(...,BACE_2,1,Train,8.853872,657.81073,2.6412,5,4,16,...,73.817162,47.171600,365.676940,174.076750,34.923889,7.980170,24.148668,0.000000,24.663788,2
2,S1(=O)(=O)N(c2cc(cc3c2n(cc3CC)CC1)C(=O)N[C@H](...,BACE_3,1,Train,8.698970,591.74091,2.5499,4,3,11,...,70.365707,47.941147,192.406520,255.752550,23.654478,0.230159,15.879790,0.000000,24.663788,3
3,S1(=O)(=O)C[C@@H](Cc2cc(O[C@H](COCC)C(F)(F)F)c...,BACE_4,1,Train,8.698970,591.67828,3.1680,4,3,12,...,56.657166,37.954151,194.353040,202.763350,36.498634,0.980913,8.188327,0.000000,26.385181,4
4,S1(=O)(=O)N(c2cc(cc3c2n(cc3CC)CC1)C(=O)N[C@H](...,BACE_5,1,Train,8.698970,629.71283,3.5086,3,3,11,...,78.945702,39.361153,179.712880,220.461300,23.654478,0.230159,15.879790,0.000000,26.100143,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1508,Clc1cc2nc(n(c2cc1)C(CC(=O)NCC1CCOCC1)CC)N,BACE_1543,0,Test,3.000000,364.86969,2.5942,3,2,6,...,37.212799,37.681076,180.226410,95.670128,30.107586,9.368159,7.980170,0.000000,0.000000,1543
1509,Clc1cc2nc(n(c2cc1)C(CC(=O)NCc1ncccc1)CC)N,BACE_1544,0,Test,3.000000,357.83731,2.8229,3,2,6,...,45.792797,47.349350,122.401500,99.877144,30.107586,9.368159,7.980170,0.000000,0.000000,1544
1510,Brc1cc(ccc1)C1CC1C=1N=C(N)N(C)C(=O)C=1,BACE_1545,0,Test,2.953115,320.18451,3.0895,2,1,2,...,47.790600,22.563574,96.290794,58.798935,20.071724,9.368159,0.000000,6.904104,0.000000,1545
1511,O=C1N(C)C(=NC(=C1)C1CC1c1cc(ccc1)-c1ccccc1)N,BACE_1546,0,Test,2.733298,317.38440,3.8595,2,1,3,...,77.219978,9.316234,95.907784,112.609720,20.071724,9.368159,0.000000,6.904104,0.000000,1546
1512,Clc1cc2nc(n(c2cc1)CCCC(=O)NCC1CC1)N,BACE_1547,0,Test,2.544546,306.79059,3.4271,2,2,6,...,26.907076,37.681076,161.450780,40.882919,30.107586,9.368159,7.980170,0.000000,0.000000,1547

In [4]:
ac = AccutuningChemicalConverter(['mol'], 'smiles', 'ecfp', 512, ['QED',])

In [5]:
ac.fit_transform(bace[:500])

,mol_0,mol_1,mol_2,mol_3,mol_4,mol_5,mol_6,mol_7,mol_8,mol_9,...,PEOE7 (PEOE7),PEOE8 (PEOE8),PEOE9 (PEOE9),PEOE10 (PEOE10),PEOE11 (PEOE11),PEOE12 (PEOE12),PEOE13 (PEOE13),PEOE14 (PEOE14),canvasUID,QED
0,0,1,0,0,0,0,0,0,0,0,...,78.640335,226.855410,107.434910,37.133846,0.000000,7.980170,0.0,0.000000,1,0.59
1,0,1,0,0,1,0,0,0,0,0,...,47.171600,365.676940,174.076750,34.923889,7.980170,24.148668,0.0,24.663788,2,0.22
2,1,1,0,0,0,0,0,0,0,0,...,47.941147,192.406520,255.752550,23.654478,0.230159,15.879790,0.0,24.663788,3,0.25
3,0,1,0,1,0,1,0,0,0,0,...,37.954151,194.353040,202.763350,36.498634,0.980913,8.188327,0.0,26.385181,4,0.29
4,1,1,0,0,0,0,0,0,0,0,...,39.361153,179.712880,220.461300,23.654478,0.230159,15.879790,0.0,26.100143,5,0.25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,0,1,0,0,0,0,0,0,0,0,...,50.027214,134.316940,94.738045,31.029167,3.271739,7.980170,0.0,6.970751,526,0.79
496,0,0,0,0,0,0,0,0,0,0,...,32.145683,151.730300,66.489906,20.071724,3.556777,7.980170,0.0,0.000000,527,0.81
497,1,0,0,0,1,0,0,0,0,0,...,65.134514,73.280083,178.236110,27.411821,3.271739,0.000000,0.0,0.000000,528,0.57
498,0,1,0,1,1,0,0,0,0,0,...,45.445873,299.932980,141.958240,38.885937,15.387257,8.188327,0.0,24.663788,529,0.49
499,0,1,0,0,0,0,0,0,0,0,...,51.392601,236.538190,154.628540,17.708305,0.000000,15.879790,0.0,24.663788,530,0.41

In [6]:
lipho = pd.read_csv("Lipophilicity.csv")

In [7]:
lipho

      CMPD_CHEMBLID   exp                                             smiles
0      CHEMBL596271  3.54            Cn1c(CN2CCN(CC2)c3ccc(Cl)cc3)nc4ccccc14
1     CHEMBL1951080 -1.18  COc1cc(OC)c(cc1NC(=O)CSCC(=O)O)S(=O)(=O)N2C(C)...
2        CHEMBL1771  3.69             COC(=O)[C@@H](N1CCc2sccc2C1)c3ccccc3Cl
3      CHEMBL234951  3.37  OC[C@H](O)CN1C(=O)C(Cc2ccccc12)NC(=O)c3cc4cc(C...
4      CHEMBL565079  3.10  Cc1cccc(C[C@H](NC(=O)c2cc(nn2C)C(C)(C)C)C(=O)N...
...             ...   ...                                                ...
4195   CHEMBL496929  3.85            OCCc1ccc(NC(=O)c2cc3cc(Cl)ccc3[nH]2)cc1
4196   CHEMBL199147  3.21  CCN(C1CCN(CCC(c2ccc(F)cc2)c3ccc(F)cc3)CC1)C(=O...
4197    CHEMBL15932  2.10                                 COc1cccc2[nH]ncc12
4198   CHEMBL558748  2.65                    Clc1ccc2ncccc2c1C(=O)NCC3CCCCC3
4199   CHEMBL237889  2.70                 CN1C(=O)C=C(CCc2ccc3ccccc3c2)N=C1N

[4200 rows x 3 columns]

In [8]:
ac = AccutuningChemicalConverter(['smiles'], 'smiles', 'ecfp', 512, ['QED' , 'MW', 'ALOGP', 'HBA', 'HBD', 'PSA'])

In [9]:
ac.fit_transform(lipho)

,CMPD_CHEMBLID,exp,smiles_0,smiles_1,smiles_2,smiles_3,smiles_4,smiles_5,smiles_6,smiles_7,...,smiles_508,smiles_509,smiles_510,smiles_511,QED,MW,ALOGP,HBA,HBD,PSA
0,CHEMBL596271,3.54,0,0,0,1,0,0,0,0,...,0,0,0,0,0.73,340.86,3.55,3,0,24.30
1,CHEMBL1951080,-1.18,1,0,0,0,0,0,0,1,...,0,0,0,0,0.55,494.59,2.99,8,2,122.24
2,CHEMBL1771,3.69,0,1,0,0,0,0,0,0,...,0,0,0,0,0.81,321.83,3.67,3,0,29.54
3,CHEMBL234951,3.37,0,1,0,0,0,1,0,0,...,0,0,1,0,0.51,419.89,1.92,4,4,105.66
4,CHEMBL565079,3.10,0,1,0,0,0,0,0,0,...,0,0,0,0,0.75,381.48,2.01,4,2,99.81
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4195,CHEMBL496929,3.85,0,0,0,0,0,0,0,0,...,0,0,0,0,0.69,314.77,3.61,2,3,65.12
4196,CHEMBL199147,3.21,0,1,0,1,0,0,0,0,...,0,0,0,0,0.33,554.70,5.45,4,0,57.69
4197,CHEMBL15932,2.10,1,0,0,0,0,0,0,0,...,0,0,0,1,0.67,148.16,1.57,2,1,37.91
4198,CHEMBL558748,2.65,0,0,1,0,1,0,0,0,...,0,0,0,0,0.92,302.81,4.20,2,1,41.99
4199,CHEMBL237889,2.70,0,0,0,0,0,0,0,0,...,0,0,0,0,0.80,279.34,2.30,3,1,60.91

In [10]:
ac = AccutuningChemicalConverter(['smiles'], 'smiles', 'tokenize', 512, ['QED' , 'MW', 'ALOGP', 'HBA', 'HBD', 'PSA'])

In [11]:
ac.fit_transform(lipho[:100])

,CMPD_CHEMBLID,exp,smiles_0,smiles_1,smiles_2,smiles_3,smiles_4,smiles_5,smiles_6,smiles_7,...,smiles_60,smiles_61,smiles_62,smiles_63,QED,MW,ALOGP,HBA,HBD,PSA
0,CHEMBL596271,3.54,0,308,21,71,12,286,22,280,...,1,1,1,1,0.73,340.86,3.55,3,0,24.30
1,CHEMBL1951080,-1.18,0,282,21,261,12,279,13,71,...,1,1,1,1,0.55,494.59,2.99,8,2,122.24
2,CHEMBL1771,3.69,0,307,263,51,272,39,36,44,...,1,1,1,1,0.81,321.83,3.67,3,0,29.54
3,CHEMBL234951,3.37,0,51,33,39,12,268,21,267,...,1,1,1,1,0.51,419.89,1.92,4,4,105.66
4,CHEMBL565079,3.10,0,267,21,276,12,39,63,39,...,1,1,1,1,0.75,381.48,2.01,4,2,99.81
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,CHEMBL2171169,2.20,0,262,12,39,13,50,12,371,...,21,51,2,1,0.26,540.67,2.25,9,5,163.68
96,CHEMBL2216830,2.04,0,39,33,262,263,51,13,277,...,1,1,1,1,0.14,656.62,6.61,8,2,112.16
97,CHEMBL381098,4.49,0,380,21,71,12,267,22,269,...,1,1,1,1,0.48,456.56,5.14,3,0,44.00
98,CHEMBL284275,0.20,0,282,21,264,12,267,22,71,...,1,1,1,1,0.72,218.26,1.17,4,3,89.95
99,CHEMBL2177167,2.00,0,280,12,280,12,39,13,39,...,1,1,1,1,0.49,469.57,1.95,8,2,134.41

In [12]:
qm = pd.read_csv("qm8.csv")

In [13]:
qm

,smiles,E1-CC2,E2-CC2,f1-CC2,f2-CC2,E1-PBE0,E2-PBE0,f1-PBE0,f2-PBE0,E1-PBE0.1,E2-PBE0.1,f1-PBE0.1,f2-PBE0.1,E1-CAM,E2-CAM,f1-CAM,f2-CAM
0,[H]C([H])([H])[H],0.432952,0.432960,0.249728,0.249736,0.430218,0.430236,0.181436,1.815015e-01,0.430218,0.430236,0.181436,1.815015e-01,0.409931,0.409939,0.1832,0.1832
1,[H]N([H])[H],0.265220,0.350081,0.067015,0.030049,0.268386,0.349106,0.040761,3.164115e-02,0.268386,0.349106,0.040761,3.164115e-02,0.253853,0.334481,0.0575,0.0238
2,[H]O[H],0.286537,0.363579,0.037755,0.000000,0.291377,0.362091,0.019503,1.000000e-08,0.291377,0.362091,0.019503,1.000000e-08,0.278519,0.350074,0.0333,0.0000
3,[H]C#C[H],0.358629,0.358629,0.000000,0.000000,0.256321,0.268469,0.000000,0.000000e+00,0.256321,0.268469,0.000000,0.000000e+00,0.244879,0.255051,0.0000,0.0000
4,[H]C#N,0.319958,0.336074,0.000000,0.000000,0.295139,0.311657,0.000000,0.000000e+00,0.295139,0.311657,0.000000,0.000000e+00,0.283425,0.296993,0.0000,0.0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21781,[H]C([H])(N1C([H])([H])C1([H])[H])C(F)(F)F,0.271951,0.297488,0.049481,0.039746,0.279686,0.305949,0.045505,3.645832e-02,0.279686,0.305949,0.045505,3.645832e-02,0.276414,0.297798,0.0314,0.0409
21782,[H]C1([H])C([H])([H])C([H])(C(F)(F)F)C1([H])[H],0.343606,0.344621,0.044959,0.017041,0.347063,0.348212,0.003887,5.704017e-02,0.347063,0.348212,0.003887,5.704017e-02,0.336025,0.337881,0.0376,0.0107
21783,[H]N1C([H])([H])C([H])([H])C1([H])C(F)(F)F,0.256356,0.279425,0.005103,0.010683,0.264920,0.280065,0.002531,9.899310e-03,0.264920,0.280065,0.002531,9.899310e-03,0.253210,0.279390,0.0037,0.0086
21784,[H]C1([H])OC([H])(C(F)(F)F)C1([H])[H],0.271197,0.292573,0.000831,0.019204,0.279916,0.302611,0.000742,2.232390e-02,0.279916,0.302611,0.000742,2.232390e-02,0.274602,0.299852,0.0004,0.0195
21785,[H]C1([H])OC([H])([H])C1([H])C(F)(F)F,0.262279,0.284981,0.000044,0.024138,0.276903,0.292604,0.001943,2.376646e-02,0.276903,0.292604,0.001943,2.376646e-02,0.266829,0.292043,0.0001,0.0266

In [16]:
ac = AccutuningChemicalConverter(['smiles'], 'smiles', 'ecfp', 128, ['QED' , 'MW', 'ALOGP', 'HBA', 'HBD', 'PSA'])

In [17]:
ac.fit_transform(qm[:1000])

,smiles_0,smiles_1,smiles_2,smiles_3,smiles_4,smiles_5,smiles_6,smiles_7,smiles_8,smiles_9,...,E1-CAM,E2-CAM,f1-CAM,f2-CAM,QED,MW,ALOGP,HBA,HBD,PSA
0,0,0,0,0,0,0,0,0,0,0,...,0.409931,0.409939,0.1832,0.1832,0.36,16.04,0.64,0,0,0.00
1,0,0,0,0,0,0,0,0,0,0,...,0.253853,0.334481,0.0575,0.0238,0.40,17.03,0.16,1,1,35.00
2,0,0,0,0,0,0,0,0,0,0,...,0.278519,0.350074,0.0333,0.0000,0.33,18.02,-0.82,0,0,31.50
3,0,0,0,0,0,0,0,0,0,0,...,0.244879,0.255051,0.0000,0.0000,0.33,26.04,0.25,0,0,0.00
4,0,0,0,0,0,0,0,0,0,0,...,0.283425,0.296993,0.0000,0.0000,0.37,27.03,0.14,1,0,23.79
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,1,0,0,0,1,0,0,0,0,0,...,0.226405,0.242689,0.1421,0.0015,0.47,94.07,0.55,3,0,49.82
996,0,0,0,0,0,0,0,0,0,0,...,0.148912,0.184603,0.0003,0.3797,0.51,95.10,0.83,1,1,32.86
997,0,0,1,0,0,0,1,0,0,0,...,0.144355,0.189590,0.0002,0.3591,0.49,96.08,1.09,2,0,30.21
998,0,0,0,0,0,0,0,0,0,0,...,0.146876,0.191019,0.0003,0.3371,0.51,96.09,0.22,2,1,45.75
999,0,0,1,0,0,0,0,0,0,0,...,0.143377,0.200692,0.0002,0.3767,0.48,97.07,0.49,3,0,43.10

In [18]:
sampl = pd.read_csv("SAMPL.csv")

In [19]:
sampl

                                iupac                  smiles   expt    calc
0    4-methoxy-N,N-dimethyl-benzamide  CN(C)C(=O)c1ccc(cc1)OC -11.01  -9.625
1            methanesulfonyl chloride            CS(=O)(=O)Cl  -4.87  -6.219
2                   3-methylbut-1-ene                CC(C)C=C   1.83   2.452
3                     2-ethylpyrazine              CCc1cnccn1  -5.45  -5.809
4                         heptan-1-ol                CCCCCCCO  -4.21  -2.917
..                                ...                     ...    ...     ...
637                  methyl octanoate          CCCCCCCC(=O)OC  -2.04  -3.035
638                       pyrrolidine                 C1CCNC1  -5.48  -4.278
639             4-hydroxybenzaldehyde          c1cc(ccc1C=O)O  -8.83 -10.050
640                   1-chloroheptane               CCCCCCCCl   0.29   1.467
641                       1,4-dioxane                C1COCCO1  -5.06  -4.269

[642 rows x 4 columns]

In [20]:
ac = AccutuningChemicalConverter(['smiles'], 'smiles', 'tokenize', 512, ['QED' , 'MW', 'ALOGP', 'HBA', 'HBD', 'PSA'])
ac.fit_transform(sampl)

,iupac,smiles_0,smiles_1,smiles_2,smiles_3,smiles_4,smiles_5,smiles_6,smiles_7,smiles_8,...,smiles_61,smiles_62,expt,calc,QED,MW,ALOGP,HBA,HBD,PSA
0,"4-methoxy-N,N-dimethyl-benzamide",0,282,21,264,12,39,263,51,13,...,1,1,-11.01,-9.625,0.69,179.22,1.40,2,0,29.54
1,methanesulfonyl chloride,0,297,263,51,288,51,13,278,2,...,1,1,-4.87,-6.219,0.42,114.55,0.18,2,0,34.14
2,3-methylbut-1-ene,0,39,33,262,12,39,13,39,2,...,1,1,1.83,2.452,0.41,70.14,1.83,0,0,0.00
3,2-ethylpyrazine,0,294,21,404,21,2,1,1,1,...,1,1,-5.45,-5.809,0.54,108.14,1.04,2,0,25.78
4,heptan-1-ol,0,285,324,2,1,1,1,1,1,...,1,1,-4.21,-2.917,0.54,116.20,1.95,1,1,20.23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
637,methyl octanoate,0,786,263,51,13,279,2,1,1,...,1,1,-2.04,-3.035,0.44,158.24,2.52,2,0,26.30
638,pyrrolidine,0,39,21,332,21,2,1,1,1,...,1,1,-5.48,-4.278,0.43,71.12,0.37,1,1,12.03
639,4-hydroxybenzaldehyde,0,51,33,267,21,264,12,51,13,...,1,1,-8.83,-10.050,0.57,122.12,1.20,2,1,37.30
640,1-chloroheptane,0,285,551,2,1,1,1,1,1,...,1,1,0.29,1.467,0.40,134.65,3.20,0,0,0.00
641,"1,4-dioxane",0,39,21,465,21,2,1,1,1,...,1,1,-5.06,-4.269,0.42,88.11,0.03,2,0,18.46